### ISSUE TITLE
Cannot send chat messages

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#25]
After `angular-swellrt` is used, sending chat messages is broken

```
TypeError: i.model[e].chat.push is not a function
    at Object.a [as addChatMessage] (http://localhost:8000/js/app.min.js:14:31464)
    at f.t.send (http://localhost:8000/js/app.min.js:15:23159)
    at fn (eval at <anonymous> (http://localhost:8000/js/app.min.js:7:16898), <anonymous>:2:203)
    at qo.(anonymous function).compile.n.on.r (http://localhost:8000/js/app.min.js:8:3407)
    at f.$get.f.$eval (http://localhost:8000/js/app.min.js:6:5499)
    at f.$get.f.$apply (http://localhost:8000/js/app.min.js:6:5725)
    at HTMLElement.<anonymous> (http://localhost:8000/js/app.min.js:8:3459)
    at HTMLElement.Z.event.dispatch (http://localhost:8000/js/app.min.js:2:15875)
    at HTMLElement.Z.event.add.v.handle (http://localhost:8000/js/app.min.js:2:12650)
```

**Comment by atfornes** [comment]
closed by P2Pvalue/angular-swellrt#9e9297a
