### ISSUE TITLE
TypeError: b.getDelegate is not a function

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#29]
When trying to post to the pad, I get this error:

```
"TypeError: b.getDelegate is not a function
    at Object.f.edit (swellrt-0.js:3495:95)
    at Array.<anonymous> (http://192.168.1.112:8000/js/app.min.js:14:8248)
    at Object.<anonymous> (http://192.168.1.112:8000/js/app.min.js:8:9700)
    at f.$get.f.$digest (http://192.168.1.112:8000/js/app.min.js:6:4045)
    at f.$get.f.$apply (http://192.168.1.112:8000/js/app.min.js:6:5766)
    at es.$$debounceViewValueCommit (http://192.168.1.112:8000/js/app.min.js:8:9477)
    at es.$setViewValue (http://192.168.1.112:8000/js/app.min.js:8:9203)
    at HTMLTextAreaElement.l (http://192.168.1.112:8000/js/app.min.js:6:21811)
    at HTMLTextAreaElement.Z.event.dispatch (http://192.168.1.112:8000/js/app.min.js:2:15875)
    at HTMLTextAreaElement.Z.event.add.v.handle (http://192.168.1.112:8000/js/app.min.js:2:12650)"
```

**Comment by atd** [comment]
Probably in SwellRT

https://github.com/P2Pvalue/swellrt/issues/29

**Comment by atfornes** [comment]
solved by https://github.com/P2Pvalue/pear2pear/commit/a97ac65080d11623f9a2fc1e4d9a02f353f5075e, it was a forgotten rich text editor div in the code :sad: sorry!
